### ISSUE TITLE
Generation of code from current spdx model.jsonld fails

### ISSUE THREAD

**Issue by maxhbr** [JPEWdev/shacl2code#1]
I used the following script:
```bash
#!/usr/bin/env bash

set -euo pipefail
venv=$(mktemp -d)
python -m venv $venv
. $venv/bin/activate

python -m pip install shacl2code
shacl2code -h

shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld python -o "./spdx3_0.py"
```

the help command prints the version `Version 0.0.8` and the generate command fails with:
```
Traceback (most recent call last):
  File "/tmp/tmp.06IfqrME09/bin/shacl2code", line 8, in <module>
    sys.exit(main())
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/shacl2code/main.py", line 139, in main
    return parsed_args.func(parser, parsed_args)
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/shacl2code/main.py", line 54, in handle_generate
    render.output(m)
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/shacl2code/lang/common.py", line 109, in output
    render = template.render(
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/shacl2code/lang/templates/python.j2", line 1556, in top-level template code
    {{ abort("Unknown data type " + prop.datatype) -}}
  File "/tmp/tmp.06IfqrME09/lib/python3.10/site-packages/shacl2code/lang/common.py", line 67, in abort_helper
    raise TemplateRuntimeError(msg)
jinja2.exceptions.TemplateRuntimeError: Unknown data type https://spdx.org/rdf/v3/Core/DateTime
```

### Debug info:
```
$ python --version
Python 3.10.14
```

**Comment by JPEWdev** [comment]
This is because the published model is out of date which is what causes this problem. You'll need to checkout the latest version of the spec parser and generate a new model, then pass that to shacl2code. Also, there are some outstanding PRs on the spec parser you'll need to apply manually, critically https://github.com/spdx/spec-parser/pull/111. As stated, there are a lot of pending changes to the SPDX model and spec parser that are needed before we can generate bindings without local changes

**Comment by JPEWdev** [comment]
Also, there is insufficient information in the base SPDX model for shacl2code to function; namely it needs to know that `@id` -> `spdxId` for Elements. I've tried to argue these should be in the model itself because the model isn't very useful without code to go with it, but for right now shacl2code requires an additional annotation RDF model that specifies these serialization constraints, which is the shacl2code-annotations.ttl file here: https://github.com/spdx/spdx-spec/pull/893. Ideally, the spec parser would put these annotations in the actual model, but for now this is the best I can do

**Comment by maxhbr** [comment]
resolved in https://github.com/spdx/spdx-3-serialization-prototype-playground/pull/34

**Comment by maxhbr** [comment]
Sorry, it is not resolved, the described commands in the README to generate are still not working

**Comment by JPEWdev** [comment]
Does this fix it https://github.com/spdx/spdx-3-serialization-prototype-playground/pull/35 ?
