### ISSUE TITLE
jinja2.exceptions.TemplateRuntimeError: Unknown data type https://spdx.org/rdf/v3/Core/DateTime

### ISSUE THREAD

**Issue by stanislaw** [JPEWdev/shacl2code#5]
Hey @JPEWdev,

I am trying to explore how to generate the SPDX JSON LD to a StrictDoc grammar and running now the README's SPDX/Python example.

I am getting an exception which suggests that something went outdated.

For now, I simply commented out the problematic fragment as follows:

```
                {#% if not prop.datatype in DATATYPE_CLASSES -%}
                    {{ abort("Unknown data type " + prop.datatype) -}}
                {% endif -%#}
                {#{ DATATYPE_CLASSES[prop.datatype] }}({%- if prop.pattern %}pattern=r"{{ prop.pattern }}",{%- endif %})#}
```

P.S. I have to deal a lot with issues like this one. My solution to this was to enable a periodic CI job that runs the integration tests on a daily basis. The solution is not perfect but that's how I can ensure more integrity for some of the external stuff my code depends on. Maybe it could help.

---

```
shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld python -o out.py
> shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld pytho
Traceback (most recent call last):
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/bin/shacl2code", line 8, in <module>
    sys.exit(main())
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 139, in main
    return parsed_args.func(parser, parsed_args)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 54, in handle_generate
    render.output(m)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 109, in output
    render = template.render(
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/templates/python.j2", line 1997, in top-level template code
    {{ abort("Unknown data type " + prop.datatype) -}}
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 67, in abort_helper
    raise TemplateRuntimeError(msg)
jinja2.exceptions.TemplateRuntimeError: Unknown data type https://spdx.org/rdf/v3/Core/DateTime
(.venv) strictdoc-project/shacl2code (main) $ shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld python -o out.py
> shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld pytho
Traceback (most recent call last):
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/bin/shacl2code", line 8, in <module>
    sys.exit(main())
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 139, in main
    return parsed_args.func(parser, parsed_args)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 54, in handle_generate
    render.output(m)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 109, in output
    render = template.render(
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/templates/python.j2", line 1997, in top-level template code
    {{ abort("Unknown data type " + prop.datatype) -}}
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 67, in abort_helper
    raise TemplateRuntimeError(msg)
jinja2.exceptions.TemplateRuntimeError: Unknown data type https://spdx.org/rdf/v3/Core/DateTime
(.venv) strictdoc-project/shacl2code (main) $ shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld python -o out.py
> shacl2code generate -i https://spdx.github.io/spdx-3-model/model.jsonld pytho
Traceback (most recent call last):
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/bin/shacl2code", line 8, in <module>
    sys.exit(main())
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 139, in main
    return parsed_args.func(parser, parsed_args)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/main.py", line 54, in handle_generate
    render.output(m)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 109, in output
    render = template.render(
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/templates/python.j2", line 1997, in top-level template code
    {{ abort("Unknown data type " + prop.datatype) -}}
  File "/Users/Stanislaw/workspace/projects/strictdoc-project/shacl2code/src/shacl2code/lang/common.py", line 67, in abort_helper
    raise TemplateRuntimeError(msg)
jinja2.exceptions.TemplateRuntimeError: Unknown data type https://spdx.org/rdf/v3/Core/DateTime
```

**Comment by JPEWdev** [comment]
@stanislaw The module you are using is outdated (and will be deleted soon), which is probably why it's giving you so much trouble. Please try with the latest model, annotations and context using the command:

```shell
shacl2code generate -i https://spdx.org/rdf/3.0.0/spdx-model.ttl -i https://spdx.org/rdf/3.0.0/spdx-json-serialize-annotations.ttl -x https://spdx.org/rdf/3.0.0/spdx-context.jsonld python -o spdx3.py
```

**Comment by stanislaw** [comment]
> shacl2code generate -i https://spdx.org/rdf/3.0.0/spdx-model.ttl -i https://spdx.org/rdf/3.0.0/spdx-json-serialize-annotations.ttl -x https://spdx.org/rdf/3.0.0/spdx-context.jsonld python -o spdx3.py

Yes, this command works. The one I was using I took from the README file, so that one should probably be updated.

I will close this issue then.

**Comment by JPEWdev** [comment]
Ah, very good. I just updated the README
